### ISSUE TITLE
Use Liberica JDK to simplify JavaFX setup

### ISSUE THREAD

**Issue by sanaagarwal** [jin-guo/COMP303#1]
When setting up the environment for the course, instructions ask to use OpenJDK, which does not include JavaFX and requires additional download and setup steps. Liberica JDK includes JavaFX and requires no additional setup past configuring the project to use it.

<img width="513" alt="Screen Shot 2023-01-08 at 7 16 54 PM" src="https://user-images.githubusercontent.com/103090715/211225993-0703b1c6-49f6-4e1e-898d-07b3daa1b7d1.png">
<img width="513" alt="Screen Shot 2023-01-08 at 7 17 30 PM" src="https://user-images.githubusercontent.com/103090715/211226010-6d640219-73bc-4baa-8c99-df246e782bf2.png">

**Comment by jin-guo** [comment]
Thanks! The information is now added in the instruction.
